### ISSUE TITLE
New release with Galaxy v16.07

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#60]
It appears that a [problem with downloading HTML datasets](http://dev.list.galaxyproject.org/Problem-downloading-HTML-datasets-td4670034.html) exists in Galaxy v16.04 but was fixed in Galaxy v16.07. It is a fairly significant issue because it prevents downloading FastQC reports. Would it be possible to roll out a new CloudMan release with Galaxy v16.07?

**Comment by afgane** [comment]
It's in the works. The [launcher](https://launch.usegalaxy.org/launch) has a new image (16.10) added already that will pull a file system archive with Galaxy 16.07. We're now testing all of this and are hoping to finalize the release within a week.

**Comment by afgane** [comment]
If you'd like to test it as well and let us know of any issues you encounter, I'd appreciate it.

**Comment by hackdna** [comment]
Great, thanks! Should I be using Image: "16.10; 20161012b02 (ami-7a6c266d)" and Flavor: Dev?

**Comment by afgane** [comment]
Yes. 
(keep in mind that things are in development so good for testing but things may go away and change around a bit as well)

**Comment by hackdna** [comment]
I've just launched a brand new 16.10 cluster but it's missing the indices volume:

```shell
ubuntu@ip-172-31-25-151:~$ ls -al /mnt/galaxyIndices/
total 8
drwxr-xr-x 2 galaxy galaxy 4096 Oct 20 19:25 .
drwxr-xr-x 8 root   root   4096 Oct 20 19:25 ..
ubuntu@ip-172-31-25-151:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G   12K  1.9G   1% /dev
tmpfs           377M  888K  376M   1% /run
/dev/xvda1       30G  4.0G   25G  15% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb        15G   55M   15G   1% /mnt
cm_processes    1.9G     0  1.9G   0% /run/cloudera-scm-agent/process
cvmfs2           22G   89M   22G   1% /cvmfs/data.galaxyproject.org
/dev/xvdf       200G  6.5G  194G   4% /mnt/galaxy
cvmfs2           22G   89M   22G   1% /cvmfs/main.galaxyproject.org
```

persistent_data.yml:
```yaml
cluster_name: !!python/unicode 'cm-16.10-dev'
cluster_storage_type: !!python/unicode 'volume'
cluster_type: !!python/unicode 'Galaxy'
deployment_version: 2
filesystems:
- kind: cvmfs
  mount_point: /cvmfs/data.galaxyproject.org
  name: galaxyIndices
  roles:
  - galaxyIndices
- ids:
  - !!python/unicode 'vol-06696b4877831debf'
  kind: volume
  mount_point: /mnt/galaxy
  name: galaxy
  roles:
  - galaxyTools
  - galaxyData
machine_image_id: ami-f2e0b0e5
persistent_data_version: 3
placement: us-east-1a
services:
- name: Supervisor
  roles:
  - Supervisor
- name: ProFTPd
  roles:
  - ProFTPd
- name: GalaxyReports
  roles:
  - GalaxyReports
- name: Slurmd
  roles:
  - Slurmd
- name: Nginx
  roles:
  - Nginx
- name: Slurmctld
  roles:
  - Slurmctld
  - Job manager
- home: /mnt/galaxy/galaxy-app
  name: Galaxy
  roles:
  - Galaxy
- name: Postgres
  roles:
  - Postgres
```

![screen shot 2016-10-20 at 16 02 52](https://cloud.githubusercontent.com/assets/452575/19575882/bb45ad80-96de-11e6-951e-2a3cfd48e71b.png)

There are no errors in the Cluster info log.
